"use client";
import {useEffect,useState} from "react";
import {Download,Menu,Search,Folder,Terminal,FileText} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Command,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from "@/components/ui/command";
import {PortfolioControls} from "@/components/portfolio-controls";
import {allWork,cv} from "@/lib/portfolio-data";
import {arsenal} from "@/lib/arsenal-data";
const sections=[["Work","work"],["Arsenal","arsenal"],["Experience","experience"],["About","about"],["Credentials","credentials"]];
export function PortfolioHeader({home=true}:{home?:boolean}){
 const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[active,setActive]=useState("");
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setSearch(s=>!s);}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[]);
 useEffect(()=>{if(!home)return;const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id);});},{rootMargin:"-15% 0px -65% 0px",threshold:0});sections.forEach(([,id])=>{const e=document.getElementById(id);if(e)observer.observe(e);});return()=>observer.disconnect();},[home]);
 function go(url:string){setSearch(false);setMenu(false);window.location.assign(url);}
 function tool(name:string){setSearch(false);if(home){document.getElementById("arsenal")?.scrollIntoView({behavior:"smooth"});window.dispatchEvent(new CustomEvent("portfolio:tool",{detail:name}));}else go(`/?tool=${encodeURIComponent(name)}#arsenal`);}
 return <><a href="#main" className="skip-link">Skip to content</a><header className="site-header"><div className="nav-shell"><a className="brand" href={home?"#main":"/"} aria-label="Riaz Ahmed Ansari home"><span className="brand-mark">ra<span>_</span></span><span className="brand-text">RIAZ ANSARI<small>CYBERSECURITY</small></span></a><nav id="portfolio-navigation" aria-label="Main navigation" className={menu?"is-open":""}>{sections.map(([label,id])=><a href={`${home?"":"/"}#${id}`} key={id} aria-current={active===id?"location":undefined} onClick={()=>setMenu(false)}>{label}</a>)}</nav><div className="nav-tools"><button className="search-toggle" onClick={()=>setSearch(true)} aria-label="Search portfolio"><Search size={18}/><kbd>Ctrl K</kbd></button><PortfolioControls/><a className="nav-cv" href={cv} download><Download size={16}/><span>CV</span></a><button className="menu-toggle" aria-label={menu?"Close navigation":"Open navigation"} aria-expanded={menu} aria-controls="portfolio-navigation" onClick={()=>setMenu(!menu)}><Menu size={21}/></button></div></div></header><Dialog open={search} onOpenChange={setSearch}><DialogContent className="search-dialog"><DialogHeader className="sr-only"><DialogTitle>Search portfolio</DialogTitle><DialogDescription>Find a project, tool, or section.</DialogDescription></DialogHeader><Command><CommandInput placeholder="Find a project, tool or section…" aria-label="Search projects and tools"/><CommandList><CommandEmpty>No matches. Try a tool name or security area.</CommandEmpty><CommandGroup heading="Projects & case studies">{allWork.map(p=><CommandItem key={p.id} value={`${p.title} ${p.areas.join(" ")}`} onSelect={()=>go(`/work/${p.id}`)}><Folder size={18}/><span>{p.title}<small>{p.context}</small></span></CommandItem>)}</CommandGroup><CommandGroup heading="Security arsenal">{arsenal.map(t=><CommandItem key={t.name} value={`Tool ${t.name} ${t.aliases||""} ${t.group}`} onSelect={()=>tool(t.name)}><Terminal size={18}/><span>{t.name}<small>{t.group}</small></span></CommandItem>)}</CommandGroup><CommandGroup heading="Sections">{[...sections,["Labs & investigations","labs"],["Contact & CV","contact"]].map(([label,id])=><CommandItem key={id} value={`Section ${label}`} onSelect={()=>go(`/#${id}`)}><FileText size={18}/>{label}</CommandItem>)}</CommandGroup></CommandList></Command></DialogContent></Dialog></>;
}
