export type Tool = {name:string;group:string;description:string;context:string;work:string[];aliases?:string};
export const toolGroups=["All tools","Offensive","Detection","DevSecOps","Cloud","Forensics","Languages"];
export const arsenal: Tool[] = [
 {name:"Nmap",group:"Offensive",description:"Host discovery and service enumeration for controlled network and application assessments.",context:"Internship & coursework",work:["network-security","vulnerability-assessment","web-security"]},
 {name:"Metasploit",group:"Offensive",description:"Penetration-testing framework used in controlled assessment and lab environments.",context:"Internship & labs",work:["network-security"]},
 {name:"Gobuster",group:"Offensive",description:"Web content and resource discovery during security lab practice.",context:"Coursework & labs",work:[]},
 {name:"Burp Suite",group:"Offensive",description:"HTTP request analysis and manual web security testing.",context:"Practical coursework",work:["web-security","vulnerability-assessment"]},
 {name:"SQLMap",group:"Offensive",description:"Controlled SQL injection testing as part of web-security coursework.",context:"Practical coursework",work:["web-security"]},
 {name:"OWASP ZAP",group:"Offensive",description:"Web application security testing in coursework and lab practice.",context:"Coursework & labs",work:[],aliases:"zap zed attack proxy"},
 {name:"Searchsploit",group:"Offensive",description:"Researching published exploit information to inform a controlled assessment plan.",context:"Practical coursework",work:["vulnerability-assessment"],aliases:"exploit db exploitdb"},
 {name:"Hydra",group:"Offensive",description:"Controlled authentication testing and investigation of insufficient lockout controls.",context:"Practical coursework",work:["vulnerability-assessment"]},
 {name:"Nessus",group:"Offensive",description:"Vulnerability assessment tool used across coursework and lab practice.",context:"Coursework & labs",work:[],aliases:"tenable"},
 {name:"Qualys",group:"Offensive",description:"Security assessment platform explored through coursework and lab practice.",context:"Coursework & labs",work:[]},
 {name:"BeEF",group:"Offensive",description:"Browser security testing framework explored in controlled security labs.",context:"Coursework & labs",work:[]},
 {name:"Nikto",group:"Offensive",description:"Web-server security scanning in coursework and lab practice.",context:"Coursework & labs",work:[]},
 {name:"John the Ripper",group:"Offensive",description:"Password security and recovery exercises in a lab context.",context:"Coursework & labs",work:[],aliases:"john openwall"},
 {name:"Hashcat",group:"Offensive",description:"Password auditing and hash-analysis exercises in a lab context.",context:"Coursework & labs",work:[]},
 {name:"BloodHound",group:"Offensive",description:"Active Directory relationship analysis and attack-path exploration.",context:"Isolated AD lab",work:["active-directory"]},
 {name:"Splunk",group:"Detection",description:"Centralised log investigation, correlation searches, dashboards, and lab detections.",context:"Projects & lab practice",work:["siemtrix","active-directory"]},
 {name:"Suricata",group:"Detection",description:"Network signature detection and security telemetry in a segmented ICS environment.",context:"Team final year project",work:["siemtrix"]},
 {name:"Zeek",group:"Detection",description:"Network behaviour telemetry and visibility into industrial communication.",context:"Team final year project",work:["siemtrix"]},
 {name:"Wireshark",group:"Detection",description:"Packet analysis, suspicious communication investigation, and network troubleshooting.",context:"Internship & coursework",work:["network-security","ddos"]},
 {name:"Sysmon",group:"Detection",description:"Windows endpoint telemetry for investigation and detection development.",context:"Projects & AD lab",work:["siemtrix","active-directory"]},
 {name:"Docker",group:"DevSecOps",description:"Containerised application deployments and infrastructure troubleshooting.",context:"DevSecOps internship",work:["devsecops"]},
 {name:"Kubernetes",group:"DevSecOps",description:"Container orchestration and application infrastructure configuration.",context:"DevSecOps internship",work:["devsecops"]},
 {name:"Trivy",group:"DevSecOps",description:"Vulnerability scanning integrated into application delivery workflows.",context:"DevSecOps internship",work:["devsecops"]},
 {name:"SonarQube",group:"DevSecOps",description:"Code analysis and security findings integrated with CI/CD workflows.",context:"DevSecOps internship",work:["devsecops"]},
 {name:"NGINX",group:"DevSecOps",description:"Reverse proxy, application delivery, and infrastructure configuration.",context:"DevSecOps internship",work:["devsecops"]},
 {name:"Linux",group:"DevSecOps",description:"Administration, deployment troubleshooting, and security assessment environments.",context:"Internship & coursework",work:["devsecops","vulnerability-assessment"]},
 {name:"Kali Linux",group:"DevSecOps",description:"Security lab environment for assessment, reconnaissance, and investigation tools.",context:"Coursework & labs",work:[],aliases:"kali"},
 {name:"Git",group:"DevSecOps",description:"Version control and collaborative application-delivery workflows.",context:"Engineering practice",work:["devsecops"]},
 {name:"AWS",group:"Cloud",description:"Cloud enumeration, resource exposure, and identity-permission lab practice.",context:"MCRTA certification labs",work:["cloud"]},
 {name:"Azure",group:"Cloud",description:"Cloud security and identity-permission learning through MCRTA lab practice.",context:"MCRTA certification labs",work:["cloud"]},
 {name:"GCP",group:"Cloud",description:"Cloud resource access and permission analysis in certification environments.",context:"MCRTA certification labs",work:["cloud"],aliases:"google cloud"},
 {name:"Autopsy",group:"Forensics",description:"Discussed during digital-forensics investigation coursework.",context:"Coursework familiarity",work:["forensics"]},
 {name:"EnCase",group:"Forensics",description:"Discussed alongside evidence acquisition and investigation methodology.",context:"Coursework familiarity",work:["forensics"]},
 {name:"FTK",group:"Forensics",description:"Discussed as part of digital-forensics tools and investigation concepts.",context:"Coursework familiarity",work:["forensics"]},
 {name:"Python",group:"Languages",description:"Security automation, API development, traffic features, and machine-learning experiments.",context:"Hands-on project work",work:["siemtrix","ddos"]},
 {name:"Bash",group:"Languages",description:"Linux scripting and command-line workflows for labs and infrastructure.",context:"Hands-on practice",work:["devsecops"]},
 {name:"PowerShell",group:"Languages",description:"Windows security workflows and PowerShell logging in lab environments.",context:"Projects & lab practice",work:["siemtrix","active-directory"]}
];
export const knowledge=["OWASP Top 10","MITRE ATT&CK","Chain of custody","Evidence acquisition","Network segmentation","Authentication & access control","Secure SDLC","Threat modelling","IAM fundamentals","Cryptography fundamentals"];
