export const github = "https://github.com/Riz18255";
export const linkedin = "https://www.linkedin.com/in/ahmed-ansari-727014168/";
export const cv = "/RiazAhmedAnsari_CV.pdf";
export const areas = ["All work", "Blue team", "Red team", "DevSecOps", "Cloud security", "ICS / OT"];
export type Work = { id: string; title: string; subtitle: string; context: string; year: string; areas: string[]; summary: string; stack: string[]; metric: string; metricLabel: string; challenge: string; contribution: string[]; outcome: string; learning: string; repo?: string; };
export const projects: Work[] = [
 { id: "siemtrix", title: "SIEMTRIX", subtitle: "ICS monitoring, detection & automated response", context: "Team final year project", year: "2025–2026", areas: ["Blue team", "ICS / OT"], summary: "A segmented industrial security platform connecting command governance, hybrid detection, and centralized visibility across IT, DMZ, OT, and sensor zones.", stack: ["Splunk", "FastAPI", "Suricata", "Zeek", "Isolation Forest", "Modbus TCP"], metric: "<148 ms", metricLabel: "average command latency in integration testing", challenge: "Provide visibility and controlled command delivery between enterprise and industrial environments while preserving segmentation and a 200 ms latency target.", contribution: ["Built and integrated the IT Zone frontend and backend for command submission and tracking.", "Integrated multi-zone Splunk logging, correlation searches, and dashboards to make the command lifecycle visible.", "Developed the Isolation Forest anomaly detection component and contributed to dataset preprocessing, attack scripting, MITRE ATT&CK for ICS mapping, and integration testing."], outcome: "The reported integration test delivered 500 concurrent commands with 100% delivery, zero message loss, and average latency below 148 ms against a 200 ms SLA. These figures describe command delivery rather than ML detection accuracy.", learning: "Industrial security needs observable command handling as well as threat detection. Correlating events across zones makes failures and decisions easier to investigate.", repo: "https://github.com/zainos-blip/SIEMTRIX" },
 { id: "ddos", title: "Real-Time ML-DDoS", subtitle: "Live network threat detection", context: "Academic project", year: "2025", areas: ["Blue team", "Network security"], summary: "A live traffic pipeline that extracts network features, classifies malicious patterns, and produces alerts for SYN flood and HTTP flood activity.", stack: ["Python", "Traffic analysis", "Feature engineering", "XGBoost", "Isolation Forest"], metric: "SYN + HTTP", metricLabel: "flood scenarios covered", challenge: "Turn live network traffic into actionable signals for connection flooding and application-layer request flooding.", contribution: ["Built a continuous pipeline for live traffic capture and feature extraction.", "Combined feature engineering with machine-learning classification and experimented with XGBoost and Isolation Forest.", "Implemented automated monitoring and real-time alerts for suspicious traffic patterns."], outcome: "Demonstrated a capture-to-alert workflow for SYN flood and HTTP flood scenarios, combining continuous traffic analysis with automated classification and alert generation.", learning: "Useful ML detection depends on consistent traffic features and alerts an analyst can investigate, as well as a model prediction." },
 { id: "active-directory", title: "Active Directory Lab", subtitle: "Attack emulation & detection", context: "Isolated security lab", year: "2025", areas: ["Red team", "Blue team"], summary: "An isolated enterprise lab connecting adversary emulation with Windows telemetry, Splunk investigations, and MITRE ATT&CK-mapped detections.", stack: ["Active Directory", "BloodHound", "Sysmon", "Splunk", "MITRE ATT&CK"], metric: "Attack → evidence", metricLabel: "offensive activity paired with defensive investigation", challenge: "Understand how identity and configuration weaknesses create attack paths, then examine the host evidence those actions leave behind.", contribution: ["Built an isolated Active Directory environment for controlled reconnaissance, credential access, privilege escalation, and lateral-movement exercises.", "Used BloodHound and offensive security tooling to explore relationships and attack paths.", "Integrated Windows and Sysmon telemetry with Splunk to investigate activity and develop detections mapped to MITRE ATT&CK."], outcome: "Created a repeatable lab workflow that pairs attack activity with telemetry and investigation in a controlled environment.", learning: "Offensive knowledge becomes more useful when each technique is connected to its prerequisites, evidence, and practical defensive controls." },
 { id: "devsecops", title: "Secure deployment pipelines", subtitle: "Container infrastructure & CI/CD security", context: "Internship work · Sysreforms", year: "2024", areas: ["DevSecOps"], summary: "Containerized deployments backed by Kubernetes and MySQL, with vulnerability scanning built into the development and delivery workflow.", stack: ["Kubernetes", "Docker", "Trivy", "SonarQube", "Linux", "NGINX"], metric: "30%", metricLabel: "reduction in deployment time", challenge: "Improve deployment efficiency while identifying and resolving vulnerabilities in the application delivery workflow.", contribution: ["Deployed and configured Kubernetes and MySQL clusters for containerized applications.", "Integrated Trivy and SonarQube into CI/CD pipelines and helped remediate more than 15 vulnerabilities.", "Secured and troubleshot Docker, Linux, NGINX, SSH, and CI/CD environments."], outcome: "The internship work reduced deployment time by 30% and remediated 15+ vulnerabilities.", learning: "Security checks are most effective when they are part of everyday delivery and produce findings the team can act on." },
 { id: "cloud", title: "Multi-cloud security labs", subtitle: "AWS, Azure & GCP attack paths", context: "MCRTA certification labs", year: "2026", areas: ["Red team", "Cloud security"], summary: "Hands-on cloud lab practice exploring exposed resources, identity permissions, and the paths between an initial foothold and sensitive cloud assets.", stack: ["AWS", "Azure", "GCP", "IAM", "Cloud enumeration"], metric: "3 platforms", metricLabel: "AWS, Azure, and Google Cloud lab practice", challenge: "Understand how cloud identity, permissions, and resource exposure influence an attack path across different providers.", contribution: ["Completed Multi-Cloud Red Team Analyst certification and practical lab work across AWS, Azure, and GCP.", "Practiced cloud enumeration, resource access checks, and identity-permission analysis in controlled certification environments.", "Connected offensive findings to least-privilege access and exposure-reduction principles."], outcome: "Earned the MCRTA certification from CyberWarFare Labs and developed practical familiarity with cloud attack surfaces through certification lab experience.", learning: "Cloud attack paths often depend on identity and permission relationships. Reading those relationships is as important as finding an exposed endpoint." }
];
export const work = ["active-directory", "ddos", "siemtrix", "devsecops", "cloud"].map(id => projects.find(project => project.id === id)!);

export const coursework: Work[] = [
 { id:"forensics", title:"Digital Forensics", subtitle:"Investigation scenarios & evidence handling", context:"University coursework · group activities", year:"2025", areas:["Blue team","Forensics"], summary:"Evidence acquisition, chain of custody, imaging and recovery concepts explored through NTFS and removable-media investigation scenarios.", stack:["Evidence acquisition","NTFS","Chain of custody","Forensic reporting"], metric:"Evidence integrity", metricLabel:"documented handling and investigation methodology", challenge:"Work through an investigation method that preserves evidence integrity and makes the reasoning and findings clear to another reviewer.", contribution:["Worked through evidence acquisition, bit-stream imaging, deleted-file recovery, and evidence-logging concepts in coursework investigation scenarios.","Examined scenarios involving NTFS and removable-media evidence and structured the investigation around chain-of-custody principles.","Contributed to group investigation discussions, documentation, and presentation work. Coursework included discussion of Autopsy, EnCase, and FTK."], outcome:"Developed investigation methodology, evidence documentation, and structured forensic reporting through practical coursework scenarios and group activities.", learning:"A forensic conclusion needs a traceable route back to the evidence. Clear handling records and a well-structured report matter alongside the analysis itself." },
 { id:"vulnerability-assessment", title:"Linux Vulnerability Assessment", subtitle:"Servers, internal applications & authentication controls", context:"University security assessment", year:"2025", areas:["Red team","App security","Network security"], summary:"A controlled assessment scenario examining Linux services, outdated components, internal web applications and insufficient login lockout controls.", stack:["Nmap","Searchsploit","Burp Suite","Hydra","Linux"], metric:"Findings to fixes", metricLabel:"assessment, impact analysis and remediation", challenge:"Identify weaknesses in a Linux server and internal web application scenario, explain their potential impact, and plan appropriate validation and remediation.", contribution:["Completed reconnaissance and attack-planning exercises around Linux servers and internal web applications.","Examined outdated SSH/kernel components and a login mechanism without adequate lockout controls using Nmap, Searchsploit, Burp Suite, and Hydra across the coursework.","Documented vulnerabilities, potential impact, exploitation approaches, and recommended remediation in a controlled assessment context."], outcome:"Produced documented assessment findings and an attack plan with remediation recommendations for service exposure, outdated components, and authentication weaknesses.", learning:"A useful assessment distinguishes a possible weakness from a validated finding and explains what an owner can do to reduce the risk." },
 { id:"web-security", title:"Web Application Security", subtitle:"PHP / MySQL / Apache assessment", context:"University case study · report & presentation", year:"2024–2025", areas:["Red team","App security"], summary:"A coursework assessment of a PHP/MySQL/Apache application, supported by a technical report and presentation. Wider labs covered selected OWASP vulnerability classes.", stack:["Burp Suite","SQLMap","Nmap","OWASP Top 10","PHP / MySQL / Apache"], metric:"Test. Explain. Fix.", metricLabel:"controlled testing and technical reporting", challenge:"Assess an application in a controlled environment and communicate security findings, their impact, and recommended fixes.", contribution:["Completed OWASP-style testing coursework covering SQL injection, XSS, CSRF, authentication/session weaknesses, access-control issues, and input validation.","Used Burp Suite, Nmap, and SQLMap across this work for discovery, request analysis, and controlled validation.","Assessed a PHP/MySQL/Apache-based web application and produced a technical report and presentation."], outcome:"Delivered a coursework web security assessment with technical reporting and presentation work. The wider coursework covered multiple OWASP topics; those topics are not represented as confirmed findings in every assessed application.", learning:"Good web testing connects a reproducible behaviour to its security impact and a specific fix. Reporting the scope of each test accurately is part of the work." }
];
export const networkWork: Work = {
 id:"network-security",title:"Network Security",subtitle:"Traffic investigation & segmented network controls",
 context:"HTR internship · university coursework",year:"2024",areas:["Network security","Blue team"],
 summary:"Network reconnaissance, packet analysis, and segmentation work during my HTR Technologies internship, supported by Computer Networks and Network Security coursework and labs.",
 stack:["Nmap","Wireshark","Metasploit","VLANs & ACLs","Routing / DHCP / NAT"],
 metric:"3",metricLabel:"unauthorised access attempts investigated during the internship",
 challenge:"Understand exposed services and suspicious communication, then connect traffic evidence to the controls that govern access between network segments.",
 contribution:["Performed reconnaissance, traffic analysis, and controlled security assessments with Nmap, Wireshark, and Metasploit at HTR Technologies.","Investigated three unauthorised access attempts through packet analysis and suspicious communication patterns.","Worked on segmented networks using VLANs, ACLs, routing, DHCP, and NAT.","Completed Computer Networks & Lab and Network Security & Lab coursework as part of my cybersecurity degree."],
 outcome:"Investigated three access attempts and gained practical experience assessing traffic and working with segmented network controls. University coursework and labs provided the underlying networking and security foundation.",
 learning:"Packet evidence is more useful when it is understood alongside the network topology and access rules. Segmentation, routing, and service configuration all influence what an analyst observes."
};
export const allWork = [work[0],coursework[0],work[1],coursework[2],work[2],networkWork,coursework[1],work[3],work[4]];
export const workAreas = ["All work","Red team","Blue team","Network security","App security","Forensics","DevSecOps","Cloud security","ICS / OT"];
export const projectFlows: Record<string,string[]> = {
 "network-security":["Discover","Analyse traffic","Investigate","Segment"],"active-directory":["Identity","Attack path","Telemetry","Detection"],"ddos":["Traffic","Features","Classification","Alerts"],"siemtrix":["IT commands","DMZ validation","OT execution","Visibility"],"devsecops":["Commit","Scan","Remediate","Deploy"],"cloud":["Resources","Identity","Permissions","Exposure"],"forensics":["Acquire","Preserve","Examine","Report"],"vulnerability-assessment":["Discover","Assess","Validate","Remediate"],"web-security":["Map surface","Test controls","Validate","Report"]
};
